### ISSUE TITLE
please add hid support (hidg*)

### ISSUE THREAD

**Issue by MrRob0-X** [Chatur27/Eureka-kernel-for-SM-A307-Q#2]
i faced this problem: https://ibb.co/GRD3GzM

even when i fix it, didn't appear hidg* in dev directory

tried everything, from patch to edit f_hid.c but nothing

so i hope that u guys fix this.

Regards 
MrRob0-X

**Comment by Chatur27** [comment]
Hi, I will see to it when I get time.

**Comment by MrRob0-X** [comment]
any news?

**Comment by MrRob0-X** [comment]
> Hi, I will see to it when I get time.

any news?

**Comment by MrRob0-X** [comment]
@Chatur27 any news?
